<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>DvMod.RemoteDispatch</RootNamespace>
    <InformationalVersion>1.2.1</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1"/>
    <Publicize Include="Assembly-CSharp" IncludeCompilerGeneratedMembers="false"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="DV.BrakeSystem"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.BrakeSystem.dll</HintPath></Reference>
    <Reference Include="DV.Simulation"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.Simulation.dll</HintPath></Reference>
    <Reference Include="DV.Common"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.Common.dll</HintPath></Reference>
    <Reference Include="DV.Interaction"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.Interaction.dll</HintPath></Reference>
    <Reference Include="DV.PointSet"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.PointSet.dll</HintPath></Reference>
    <Reference Include="DV.RailTrack"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.RailTrack.dll</HintPath></Reference>
    <Reference Include="DV.ThingTypes"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.ThingTypes.dll</HintPath></Reference>
    <Reference Include="DV.Utils"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\DV.Utils.dll</HintPath></Reference>
    <Reference Include="Microsoft.CSharp"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\Microsoft.CSharp.dll</HintPath></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\Newtonsoft.Json.dll</HintPath></Reference>
    <Reference Include="net.smkd.vector3d"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\net.smkd.vector3d.dll</HintPath></Reference>
    <Reference Include="WorldStreamer"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\WorldStreamer.dll</HintPath></Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath Condition="'$(DVManagedPath)' != ''">$(DVManagedPath)\UnityEngine.IMGUIModule.dll</HintPath></Reference>
    <PackageReference Include="UnityModManager" Version="0.27.2"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.svg"/>
    <EmbeddedResource Include="index.html"/>
    <EmbeddedResource Include="leaflet.rotatedImageOverlay.js"/>
    <EmbeddedResource Include="licenses/*.png"/>
    <EmbeddedResource Include="main.js"/>
    <EmbeddedResource Include="style.css"/>
  </ItemGroup>
</Project>
